[[language]]
name = "c"
file-types = ["c", "h"]
formatter = { command = 'clang-format' }
auto-format = true

[[language]]
name = "cpp"
file-types = ["cpp", "cc", "cxx", "hpp", "hcc", "hxx"]
formatter = { command = 'clang-format' }
auto-format = true

[[language]]
name = "Makefile"
scope = "Makefile"
file-types = ["Makefile"]

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = ["harper-ls"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
